name: CI  # Name of the workflow (will show in GitHub Actions tab)

on:
  push:                 # Run this when you push to main or master branch
    branches: [ main, master ]
  pull_request:         # Also run when a pull request is made

jobs:
  lint-and-test:        # One job called "lint-and-test"
    runs-on: ubuntu-latest  # It runs on a virtual Ubuntu machine

    steps:
      - uses: actions/checkout@v4   # Step 1: Download your repo code

      - uses: actions/setup-python@v5   # Step 2: Set up Python
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov ruff

      - name: Lint (ruff)
        run: ruff check .

      - name: Run tests
        run: pytest -q --maxfail=1 --disable-warnings --cov=src --cov-report=xml

      - name: Upload coverage.xml
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
